# Generated by Django 6.1 on 2026-09-14 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_education'),
    ]

    operations = [
        migrations.RenameField(
            model_name='education',
            old_name='supporting_subjects',
            new_name='description',
        ),
    ]
